name: Parse DOCX to JSON

on:
  push:
    paths:
      - "parser/input/**/*.docx"

jobs:
  parse-docx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-docx

      - name: Run DOCX to JSON parser
        run: |
          python parser/parse-docx-to-json.py

      - name: Configure Git
        run: |
          git config --local user.name "teanus"
          git config --local user.email "teanus.ti@gmail.com"

      - name: Commit JSON output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add parser/output/*.json
          git commit -m "Auto-parse DOCX to JSON [skip ci]" || echo "No changes to commit"
          git push origin HEAD
